-- =============================================================================
-- StockSense: Enterprise Multi-Warehouse & Granular Sub-Location / Rack Seed
-- Dynamic Autogenerated IDs (gen_random_uuid) - Safe & Idempotent
-- =============================================================================

-- Enable pgcrypto extension for UUID generation if not already active
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- -----------------------------------------------------------------------------
-- 1. SEED PRODUCT CATEGORIES (IDs Autogenerated)
-- -----------------------------------------------------------------------------
INSERT INTO categories (name, code, description, icon, status)
VALUES
  ('Sensors & IoT', 'SENSORS', 'Thermal, optical, torque, proximity, and vibration telemetry devices', 'Radar', 'Active'),
  ('Actuators', 'ACTUATORS', 'Electric motors, servo actuators, linear stages, and planetary drives', 'Cpu', 'Active'),
  ('Controllers', 'CONTROLLERS', 'Programmable logic controllers, CNC heads, and embedded compute units', 'Sliders', 'Active'),
  ('Pneumatics', 'PNEUMATICS', 'Valves, air cylinders, pressure regulators, and high-pressure tubing', 'Wind', 'Active'),
  ('Networking', 'NETWORK', 'Industrial switches, wireless gateways, fieldbus interfaces, and serial servers', 'Network', 'Active'),
  ('Power & Relays', 'POWER', '24V/48V DIN-rail power supplies, solid-state relays, and battery backups', 'Zap', 'Active'),
  ('Raw Materials', 'RAWMAT', 'Steel rods, aluminum billets, structural frames, and sheet metal', 'Boxes', 'Active'),
  ('Fasteners & Seals', 'FASTENERS', 'O-rings, high-tensile metric bolts, mounting brackets, and seals', 'Layers', 'Active')
ON CONFLICT (name) DO UPDATE 
SET 
  code = EXCLUDED.code,
  description = EXCLUDED.description,
  icon = EXCLUDED.icon,
  status = EXCLUDED.status,
  updated_at = CURRENT_TIMESTAMP;

-- -----------------------------------------------------------------------------
-- 2. SEED ENTERPRISE WAREHOUSES (IDs Autogenerated)
-- -----------------------------------------------------------------------------
INSERT INTO warehouses (name, code, address, manager_name, is_active)
VALUES
  (
    'Main Central Hub',
    'WH-MAIN',
    '100 Logistics Blvd, Oakland, CA 94607',
    'Sarah Jenkins',
    TRUE
  ),
  (
    'Production Facility East',
    'WH-PROD',
    '450 Industrial Parkway, Allentown, PA 18109',
    'Marcus Vance',
    TRUE
  ),
  (
    'Southern Logistics Depot',
    'WH-SOUTH',
    '780 Freight Way, Dallas, TX 75261',
    'Elena Rostova',
    TRUE
  ),
  (
    'West Coast Distribution',
    'WH-WEST',
    '1200 Pacific Gateway, Seattle, WA 98101',
    'Alexandria Vance',
    TRUE
  ),
  (
    'European Gateway Hub',
    'WH-EUR',
    'Rotterdam Port Sector 4, Maasvlakte, Netherlands',
    'Lars Van Der Berg',
    TRUE
  )
ON CONFLICT (code) DO UPDATE
SET 
  name = EXCLUDED.name,
  address = EXCLUDED.address,
  manager_name = EXCLUDED.manager_name,
  is_active = EXCLUDED.is_active;

-- -----------------------------------------------------------------------------
-- 3. SEED GRANULAR SUB-LOCATIONS & RACKS (IDs Autogenerated, FK dynamic)
-- -----------------------------------------------------------------------------
INSERT INTO locations (warehouse_id, name, code, type)
SELECT w.id, loc.name, loc.code, loc.type
FROM (VALUES
  -- Main Central Hub (WH-MAIN) Racks & Zones
  ('WH-MAIN', 'Inbound Dock & Receiving', 'DOCK-IN', 'INTERNAL'),
  ('WH-MAIN', 'Rack A (Sensors & Robotics)', 'RCK-A', 'INTERNAL'),
  ('WH-MAIN', 'Rack B (Controllers & PLC)', 'RCK-B', 'INTERNAL'),
  ('WH-MAIN', 'Rack C (Networking & Comm)', 'RCK-C', 'INTERNAL'),
  ('WH-MAIN', 'Quality Assurance Quarantine', 'QA-HOLD', 'SCRAP'),
  ('WH-MAIN', 'Outbound Shipping Staging', 'SHIP-BAY', 'TRANSIT'),

  -- Production Facility East (WH-PROD) Racks & Zones
  ('WH-PROD', 'Production Assembly Floor', 'PROD-FLR', 'INTERNAL'),
  ('WH-PROD', 'Raw Materials Bin Staging', 'RAW-BIN', 'INTERNAL'),
  ('WH-PROD', 'Work In Progress (WIP) Rack', 'WIP-RACK', 'INTERNAL'),
  ('WH-PROD', 'Salvage & Scrap Bin', 'SCRAP-BAY', 'SCRAP'),
  ('WH-PROD', 'Production Outbound Dock', 'DOCK-PROD', 'TRANSIT'),

  -- Southern Logistics Depot (WH-SOUTH) Racks & Zones
  ('WH-SOUTH', 'Bulk Inbound Receiving', 'DOCK-SOUTH', 'INTERNAL'),
  ('WH-SOUTH', 'High-Bay Pallet Racking A1', 'HIGH-BAY-1', 'INTERNAL'),
  ('WH-SOUTH', 'High-Bay Pallet Racking B2', 'HIGH-BAY-2', 'INTERNAL'),
  ('WH-SOUTH', 'Cross-Dock Transit Bay', 'TRANSIT-BAY', 'TRANSIT'),
  ('WH-SOUTH', 'Vendor Consignment Depot', 'VND-CONSIGN', 'VENDOR'),

  -- West Coast Distribution (WH-WEST) Racks & Zones
  ('WH-WEST', 'Fast-Moving Pick Zone 1', 'PAC-RACK-1', 'INTERNAL'),
  ('WH-WEST', 'Bulk Storage Zone 2', 'PAC-RACK-2', 'INTERNAL'),
  ('WH-WEST', 'Customer Order Staging Area', 'CUST-STAGE', 'CUSTOMER'),
  ('WH-WEST', 'Intermodal Rail Dock', 'WEST-DOCK', 'TRANSIT'),

  -- European Gateway Hub (WH-EUR) Racks & Zones
  ('WH-EUR', 'Bonded Customs Staging', 'EUR-BOND-1', 'TRANSIT'),
  ('WH-EUR', 'Automated Shuttle Rack A', 'EUR-RCK-A', 'INTERNAL'),
  ('WH-EUR', 'Specialty Climate Rack B', 'EUR-RCK-B', 'INTERNAL')
) AS loc(warehouse_code, name, code, type)
JOIN warehouses w ON w.code = loc.warehouse_code
ON CONFLICT (warehouse_id, code) DO UPDATE
SET
  name = EXCLUDED.name,
  type = EXCLUDED.type;

-- -----------------------------------------------------------------------------
-- 4. SEED MASTER INDUSTRIAL PRODUCTS CATALOG (IDs Autogenerated)
-- -----------------------------------------------------------------------------
INSERT INTO products (
  name, sku, barcode, category_id, category_name, category, uom, unit,
  price, cost_price, available_qty, reserved_qty, reorder_level, warehouse, status, supplier, description, image
)
SELECT 
  p.name, p.sku, p.barcode, c.id, p.category_name, p.category_name, p.uom, p.uom,
  p.price, p.cost_price, p.available_qty, p.reserved_qty, p.reorder_level, p.warehouse, p.status, p.supplier, p.description, p.image
FROM (VALUES
  ('Industrial Torque Sensor TS-90', 'SEN-TRQ-90', '8901234567890', 'Sensors & IoT', 'pcs', 349.00, 210.00, 142, 18, 50, 'Main Central Hub', 'In Stock', 'Apex Dynamics Corp', 'High-precision industrial torque sensor with CAN bus and RS-485 interfaces.', 'Radar'),
  ('Precision Stepper Motor 24V', 'MOT-STP-24', '8901234567891', 'Actuators', 'pcs', 89.50, 52.00, 85, 12, 40, 'Main Central Hub', 'In Stock', 'Apex Dynamics Corp', 'NEMA 23 bipolar stepper motor with 1.8 degree step angle and 1.26 Nm holding torque.', 'Cpu'),
  ('Optical Laser Distance Gauge', 'SEN-OPT-04', '8901234567892', 'Sensors & IoT', 'pcs', 520.00, 340.00, 25, 5, 30, 'Main Central Hub', 'Low Stock', 'LuminoTech Precision', 'Class II optical laser rangefinder with ±1mm accuracy over 50m distance.', 'Radar'),
  ('Heavy Duty Pneumatic Cylinder', 'PNE-CYL-80', '8901234567893', 'Pneumatics', 'pcs', 145.00, 88.00, 95, 15, 35, 'Production Facility East', 'In Stock', 'Vortex Flow Systems', 'ISO 15552 standard pneumatic cylinder with adjustable end-position cushioning.', 'Wind'),
  ('Programmable Logic Controller (PLC)', 'CTL-PLC-16', '8901234567894', 'Controllers', 'pcs', 890.00, 580.00, 42, 8, 20, 'Main Central Hub', 'In Stock', 'ElectroCore Global', 'Modular PLC with 16 digital inputs, 16 relay outputs, Ethernet/IP and Modbus TCP.', 'Sliders'),
  ('Thermal Imaging Camera Module', 'CAM-THM-64', '8901234567895', 'Sensors & IoT', 'pcs', 1250.00, 810.00, 62, 4, 20, 'West Coast Distribution', 'In Stock', 'LuminoTech Precision', 'Long-wave infrared thermal camera core 640x512 with 30Hz frame rate.', 'Radar'),
  ('Industrial Ethernet Switch 8-Port', 'NET-SWT-08', '8901234567896', 'Networking', 'pcs', 275.00, 165.00, 195, 25, 40, 'Main Central Hub', 'In Stock', 'ElectroCore Global', 'DIN-rail managed Gigabit Ethernet switch with redundant DC power inputs.', 'Network'),
  ('High-Torque Planetary Gearbox 10:1', 'GBX-PLN-10', '8901234567897', 'Actuators', 'pcs', 310.00, 195.00, 28, 3, 30, 'Southern Logistics Depot', 'Low Stock', 'Apex Dynamics Corp', 'Precision low-backlash planetary reducer for servo motors.', 'Cpu'),
  ('Reinforced Hydraulic Hose 50m', 'HYD-HSE-50', '8901234567898', 'Pneumatics', 'rolls', 198.00, 115.00, 15, 2, 25, 'Southern Logistics Depot', 'Low Stock', 'Vortex Flow Systems', 'Four-spiral steel wire reinforced rubber hose rated up to 450 bar working pressure.', 'Wind'),
  ('Brushless DC Servo Drive 48V', 'DRV-BLDC-48', '8901234567899', 'Controllers', 'pcs', 430.00, 280.00, 110, 15, 35, 'Southern Logistics Depot', 'In Stock', 'ElectroCore Global', 'Digital servo drive with CANopen, EtherCAT, and integrated safety torque-off.', 'Sliders'),
  ('Carbon Steel Round Rods 25mm x 2m', 'STL-ROD-01', '8901234567800', 'Raw Materials', 'pcs', 45.00, 28.00, 260, 20, 50, 'Production Facility East', 'In Stock', 'Titanium Mechanical Inc', 'Cold-rolled carbon steel round rods for production and fabrication.', 'Boxes'),
  ('DIN-Rail Power Supply 24V 10A', 'PWR-DIN-24', '8901234567801', 'Power & Relays', 'pcs', 115.00, 72.00, 88, 10, 30, 'West Coast Distribution', 'In Stock', 'ElectroCore Global', 'Ultra-slim DIN-rail AC/DC industrial switched-mode power supply 240W.', 'Zap')
) AS p(name, sku, barcode, category_name, uom, price, cost_price, available_qty, reserved_qty, reorder_level, warehouse, status, supplier, description, image)
LEFT JOIN categories c ON c.name = p.category_name
ON CONFLICT (sku) DO UPDATE
SET
  name = EXCLUDED.name,
  barcode = EXCLUDED.barcode,
  category_id = EXCLUDED.category_id,
  category_name = EXCLUDED.category_name,
  category = EXCLUDED.category,
  uom = EXCLUDED.uom,
  unit = EXCLUDED.unit,
  price = EXCLUDED.price,
  cost_price = EXCLUDED.cost_price,
  available_qty = EXCLUDED.available_qty,
  reserved_qty = EXCLUDED.reserved_qty,
  reorder_level = EXCLUDED.reorder_level,
  warehouse = EXCLUDED.warehouse,
  status = EXCLUDED.status,
  supplier = EXCLUDED.supplier,
  description = EXCLUDED.description,
  image = EXCLUDED.image,
  updated_at = CURRENT_TIMESTAMP;

-- -----------------------------------------------------------------------------
-- 5. SEED GRANULAR STOCK LEVELS PER RACK (IDs Autogenerated, dynamic mapping)
-- -----------------------------------------------------------------------------
INSERT INTO stock_levels (product_id, location_id, quantity, reserved_quantity)
SELECT 
  p.id AS product_id,
  l.id AS location_id,
  stk.quantity,
  stk.reserved_quantity
FROM (VALUES
  -- Main Central Hub -> Inbound Dock (DOCK-IN)
  ('SEN-OPT-04', 'WH-MAIN', 'DOCK-IN', 25, 5),
  ('SEN-TRQ-90', 'WH-MAIN', 'DOCK-IN', 20, 0),

  -- Main Central Hub -> Rack A Sensors & Robotics (RCK-A)
  ('SEN-TRQ-90', 'WH-MAIN', 'RCK-A', 120, 18),
  ('MOT-STP-24', 'WH-MAIN', 'RCK-A', 85, 12),

  -- Main Central Hub -> Rack B Controllers & PLC (RCK-B)
  ('CTL-PLC-16', 'WH-MAIN', 'RCK-B', 42, 8),

  -- Main Central Hub -> Rack C Networking & Comm (RCK-C)
  ('NET-SWT-08', 'WH-MAIN', 'RCK-C', 195, 25),

  -- Main Central Hub -> QA Quarantine (QA-HOLD)
  ('SEN-TRQ-90', 'WH-MAIN', 'QA-HOLD', 2, 0),
  ('MOT-STP-24', 'WH-MAIN', 'QA-HOLD', 3, 0),

  -- Production Facility East -> Production Assembly Floor (PROD-FLR)
  ('PNE-CYL-80', 'WH-PROD', 'PROD-FLR', 95, 15),

  -- Production Facility East -> Raw Materials Bin (RAW-BIN)
  ('STL-ROD-01', 'WH-PROD', 'RAW-BIN', 260, 20),

  -- Production Facility East -> Work in Progress (WIP-RACK)
  ('PNE-CYL-80', 'WH-PROD', 'WIP-RACK', 15, 0),

  -- Southern Logistics Depot -> High-Bay Pallet Racking A1 (HIGH-BAY-1)
  ('GBX-PLN-10', 'WH-SOUTH', 'HIGH-BAY-1', 28, 3),
  ('DRV-BLDC-48', 'WH-SOUTH', 'HIGH-BAY-1', 110, 15),

  -- Southern Logistics Depot -> High-Bay Pallet Racking B2 (HIGH-BAY-2)
  ('HYD-HSE-50', 'WH-SOUTH', 'HIGH-BAY-2', 15, 2),

  -- West Coast Distribution -> Fast-Moving Pick Zone 1 (PAC-RACK-1)
  ('CAM-THM-64', 'WH-WEST', 'PAC-RACK-1', 62, 4),
  ('PWR-DIN-24', 'WH-WEST', 'PAC-RACK-1', 88, 10),

  -- European Gateway Hub -> Automated Shuttle Rack A (EUR-RCK-A)
  ('CTL-PLC-16', 'WH-EUR', 'EUR-RCK-A', 30, 0),
  ('NET-SWT-08', 'WH-EUR', 'EUR-RCK-A', 75, 10)
) AS stk(sku, warehouse_code, location_code, quantity, reserved_quantity)
JOIN products p ON p.sku = stk.sku
JOIN warehouses w ON w.code = stk.warehouse_code
JOIN locations l ON l.warehouse_id = w.id AND l.code = stk.location_code
ON CONFLICT (product_id, location_id) DO UPDATE
SET
  quantity = EXCLUDED.quantity,
  reserved_quantity = EXCLUDED.reserved_quantity,
  updated_at = CURRENT_TIMESTAMP;

-- -----------------------------------------------------------------------------
-- 6. SYNC OVERALL PRODUCT AGGREGATES FROM STOCK LEVELS
-- -----------------------------------------------------------------------------
WITH agg AS (
  SELECT 
    product_id,
    SUM(quantity)::int AS total_qty,
    SUM(reserved_quantity)::int AS total_res
  FROM stock_levels
  GROUP BY product_id
)
UPDATE products p
SET 
  available_qty = agg.total_qty,
  reserved_qty = agg.total_res,
  status = CASE 
    WHEN agg.total_qty <= 0 THEN 'Out of Stock'
    WHEN agg.total_qty <= p.reorder_level THEN 'Low Stock'
    ELSE 'In Stock'
  END,
  updated_at = CURRENT_TIMESTAMP
FROM agg
WHERE p.id = agg.product_id;
